version: "3"
services:
  mongo:
    image: "mongo:3-stretch"
    container_name: "mongo"
    environment:
      MONGO_INITDB_DATABASE: objectreport
  mongo-express:
    image: "mongo-express:latest"
    container_name: "mongoex"
    ports:
      - "8081:8081"
    links:
     - mongo
  objectreport:
    build: ./objectReport
    container_name: objectreport
    ports:
      - "8000:8000"
    links:
      - mongo:mongo
    depends_on:
      - mongo
